### ISSUE TITLE
does not work with node v0.5.x

### ISSUE THREAD

**Issue by christophsturm** [brainpicture/hashlib#23]
I'd like to try running my app on node v0.5.9 but i can't because hashlib does not build on v0.5.x

<pre>
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for gcc                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /Users/christoph/.nvm/v0.5.9 
'configure' finished successfully (0.216s)
Waf: Entering directory `/Users/christoph/Projects/collmedia/petrol/node_modules/hashlib/build'
[1/6] cc: libhash/md4c.c -> build/Release/libhash/md4c_1.o
[2/6] cc: libhash/md5c.c -> build/Release/libhash/md5c_1.o
[3/6] cc: libhash/sha0c.c -> build/Release/libhash/sha0c_1.o
[4/6] cxx: hashlib.cc -> build/Release/hashlib_2.o
../hashlib.cc:14:16: error: ev.h: No such file or directory
../hashlib.cc:15:17: error: eio.h: No such file or directory
../hashlib.cc:311: error: ‘eio_req’ was not declared in this scope
../hashlib.cc:311: error: ‘req’ was not declared in this scope
../hashlib.cc:312: error: expected ‘,’ or ‘;’ before ‘{’ token
Waf: Leaving directory `/Users/christoph/Projects/collmedia/petrol/node_modules/hashlib/build'
</pre>

**Comment by subnetmarco** [comment]
+1
